### ISSUE TITLE
Notes voting

### ISSUE THREAD

**Issue by lecascyril** [belbazanas/votingSystem#1]
déclaration des events au milieu des variables

doublon des proposals - mapping jamais utilisé

constructor: la valeur par defaut de l'enum est la première, pas besoin de réassigner la variable

get winner peut retourner directement l'objet proposal plutot que la desc (pour avoir les infos)

add proposal: event emit proposal length -1

fonction set vote: ne doit pas pouvoir voter pour une autre personne, le paramètres _addr ne doit pas etre là. On vote pour soi, il y a mise a jour du vote pour msg.sender

7,5/10

**Comment by anasbelbaz** [comment]
okay okay, merci
